services:
  postgres:
    image: postgres:15
    container_name: tickets-postgres
    environment:
      POSTGRES_DB: ticketsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend_2
    container_name: tickets-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ticketsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend_1
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  postgres-data:
